### ISSUE TITLE
prone's cljs clashes with host projects' cljs

### ISSUE THREAD

**Issue by martintrojer** [magnars/prone#25]
I use https://github.com/thheller/shadow-build to build my cljs and its finding prone's cljs on the classpath and builds them into my cljs (and then it all breaks).

**Comment by magnars** [comment]
What happened?

**Comment by martintrojer** [comment]
Realised that its a dup, 

relates to #21and https://github.com/thheller/shadow-build/issues/23

**Comment by magnars** [comment]
I see. If you know enough about cljs and jars, a pull request is certainly welcome.
