### ISSUE TITLE
Prone isn't working with lein-ring

### ISSUE THREAD

**Issue by hussein** [magnars/prone#27]
Hi,

Thanks for creating this awesome library.

I'm trying to use it with lein-ring. Snippet from `project.clj`:

      :profiles {:dev {:aliases {"run-dev" ["trampoline" "run" "-m" "my-api/-main"]}
                       :ring {:stacktrace-middleware prone.middleware/wrap-exceptions}
                       :dependencies [[lein-ring "0.9.6"]]}
                 :uberjar {:aot :all}})

But that isn't taking place, nothing is happening.

What I'm doing wrong?

Lein 2.5.1, Clojure 1.7

Thanks again.

**Comment by magnars** [comment]
Hi! Could you try with `lein-ring "0.9.1"` and see if it works there?

**Comment by hussein** [comment]
Hi,

I changed it to `lein-ring 0.9.1` but still nothing is happening.

**Comment by magnars** [comment]
Could you do `lein deps :tree` and make sure you are actually using `ring-server "0.4.0"`?

**Comment by hussein** [comment]
I did and actually `ring-server` isn't a dependency at all in my project. It should a project dependency or dependency for `:dev` profile only?

**Comment by magnars** [comment]
You normally don't have to include `ring-server` yourself. What Ring packages are you including?

**Comment by hussein** [comment]
Here are my dependencies: 

      :dependencies [[org.clojure/clojure "1.7.0"]
                 [liberator "0.13"]
                 [compojure "1.4.0"]
                 [ring/ring-core "1.4.0"]
                 [ring/ring-jetty-adapter "1.4.0"]
                 [cheshire "5.5.0"]
                 [com.taoensso/timbre "4.1.0"]
                 [prone "0.8.2"]]

**Comment by magnars** [comment]
I see that `lein-ring` does [some magic to include it](https://github.com/weavejester/lein-ring/blob/master/src/leiningen/ring/server.clj#L33).

If you could make a minimal project example that reproduces the issue, I'll dig into it tonight.

**Comment by hussein** [comment]
Yes sure, thanks for help.

**Comment by magnars** [comment]
Please re-open this issue if you can reproduce it.
