### ISSUE TITLE
GPL License makes it incompatible with pretty much every Clojure library

### ISSUE THREAD

**Issue by emanchado** [magnars/prone#28]
Clojure is licensed under the Eclipse Public License, and most libraries seem to use the same license. Unfortunately, this license is incompatible with the GPL (see FSF's [own explanation](https://www.gnu.org/licenses/license-list.html#EPL)), so that makes prone legally incompatible with almost every Clojure library. In fact, I would imagine that the Clojure standard library has the same license, so I don't think it's even possible to have a legal Clojure program that uses prone :-(

The lazier/easier alternative would be to use EPL, although I would imagine that any "liberal" license (BSD and such) would work, too.

**Comment by magnars** [comment]
@cjohansen Thoughts?

**Comment by cjohansen** [comment]
My thoughts: Clojure fucked up with the ELP :) Not being able to release software with a GPL is seriously fucked up. But given the circumstances I suggest BSD, I know very little about EPL (but, using Clojure, perhaps I should learn more about it).

**Comment by magnars** [comment]
Yeah, the situation clearly sucks. BSD is fine by me.

@andrewmcveigh @rkworks @minimal - you have a few lines of code in the project. Any problems with changing the license to BSD? Or other comments?

**Comment by andrewmcveigh** [comment]
No problem changing the license to BSD for me.

Personally I've never had an issue with prone being GPL as I've never distributed it. Not something you want to ship in production IMO (well, unless you're trying to write a web-framework or something).

**Comment by cjohansen** [comment]
Prone should not be used in production.

**Comment by minimal** [comment]
Yes, feel free to change the license.

**Comment by rkworks** [comment]
No problem. Please go ahead :+1:
