### ISSUE TITLE
Prone crashes for projects with unquoted forms in project.clj

### ISSUE THREAD

**Issue by brunchboy** [magnars/prone#29]
I finally tracked down why I have stopped getting nice Prone stack traces. I suspect this began when I changed my `project.clj` to include some evaluated forms to build my Manifest entry when creating Jar files:

```clojure
;...
  :uberjar-name "afterglow.jar"
  :manifest {"Name" ~#(str (clojure.string/replace (:group %) "." "/")
                            "/" (:name %) "/")
             "Package" ~#(str (:group %) "." (:name %))
             "Specification-Title" ~#(:name %)
             "Specification-Version" ~#(:version %)}
;...
```

The reason I suspect this is the problem is that now whenever I get a runtime error, instead of the nice Prone stack trace, I simply see “Error: 500 Something very bad has happened! We've dispatched a team of highly trained gnomes to take care of the problem.” And in my log file, I get a stack trace which ends:

```
prone.middleware/wrap-exceptions/fn             middleware.clj:   94
prone.middleware/get-application-name           middleware.clj:   20
prone.middleware/get-application-name/invokeStatic           middleware.clj:   25
clojure.edn/read-string                         edn.clj:   37
clojure.edn/read-string/invokeStatic            edn.clj:   37
clojure.edn/read-string/invokeStatic            edn.clj:   46

java.lang.RuntimeException: Invalid leading character: ~
```

And, indeed, I just tried removing my `:manifest` declaration, and I get back the lovely Prone stack trace. All right, now that I know this, when I encounter a problem I can shut down my REPL, hack the `project.clj`, restart the REPL, and try to recreate the problem so I can see the actual error. But I would much prefer to have Prone be able to coexist with this kind of code in the project—as things stand, the Prone crash completely obscures the original problem that I would like to debug.

I need to keep the evaluated expressions in my project definition, in order to build name and version information which is displayed to the user at runtime when executing from a jar file, either standalone, or embedded in the Max/MSP visual programming environment. And the sample `project.clj` in Leiningen itself includes such examples, so I very much hope this is something that Prone can be made to accommodate?

**Comment by minimal** [comment]
If you explicitly pass in `{:app-namespaces ["our" "app" "namespace" "prefixes"]}` to wrap-exceptions it won't try to parse project.clj.
https://github.com/magnars/prone#how-does-prone-determine-what-parts-of-a-stack-trace-belongs-to-the-application

**Comment by brunchboy** [comment]
Thanks, that workaround works for me. It might be nice to still address the underlying crash for others in the future, because I went months without my stack traces before taking the time to narrow them down to this issue. Of course, if the web interface (and Prone itself) were a more central part of my project, I would have probably done so more quickly.

**Comment by brunchboy** [comment]
As an alternative to being able to robustly parse the project, how about failing more gracefully, for example just showing all stack frames, with a warning box explaining how to configure the application namespace prefix because Prone has been unable to parse them out of `project.clj`?

**Comment by magnars** [comment]
Prone `0.8.3` released with a fix for this one. Thanks for the report!

**Comment by brunchboy** [comment]
Nice, thanks! :+1:
