### ISSUE TITLE
An javascript error was raised when running demo application.

### ISSUE THREAD

**Issue by eunmin** [magnars/prone#30]
```
Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null
```

I receive this javascript error when running the demo application server after `lein cljsbuild auto`.

<img width="1418" alt="2016-01-02 5 55 30" src="https://cloud.githubusercontent.com/assets/1837478/12073901/2423aa50-b17a-11e5-81ae-83545f7fd054.png">

**Comment by eunmin** [comment]
Might be due to API changes in the new React version. (NPM latest version is 0.14.5)
It was solved by installing a version 0.11.1. (Prone 0.8.3 is used.)
How about specify in the `build-js-sources.sh` script to a specific version of NPM react?
Like this:

```bash
#!/bin/sh

git submodule update --init

if [ ! -d "resources/node_modules/react" ]; then
    cd resources
    npm install react@0.11.1
    cd ..
fi
```

**Comment by magnars** [comment]
We really need to overhaul how we include these js-dependencies, but yeah - this is a bare minimum. Thanks.

**Comment by eunmin** [comment]
Thanks! :+1:
