### ISSUE TITLE
putting prone under single url prefix

### ISSUE THREAD

**Issue by piranha** [magnars/prone#32]
I really like prone, but it generates urls which start with various numbers (like `/1320042293/prone.css`). And it's a bit hard to use those because of how my environment is configured (I can proxy only specific prefixes to a clojure app).

I wonder if it's possible to put it under some url like `/prone`, so the url will be `/prone/123/prone.css` or `/prone/prone.css`.

**Comment by magnars** [comment]
That sounds entirely doable. :) I'm a bit busy at work, so don't know when I get the chance. Maybe you want to take a look at it?

**Comment by piranha** [comment]
I'm in similar state, to be honest, though I'd like to. :-) Will see if I get a chance...

**Comment by magnars** [comment]
Well, that was easy. `1.0.1` released with this fix. :)

**Comment by piranha** [comment]
Oh, nice, thanks :-)
