### ISSUE TITLE
Is there a way to make prone work with ring on top of aleph?

### ISSUE THREAD

**Issue by Gonzih** [magnars/prone#37]
Hi there,

I'm using ring with aleph and I'm trying to make prone work on top of aleph. Main problem is that aleph kind of breaks ring spec by allowing to return futures as a response. Normal way to port middleware is to use let-flow that aleph provides and reuse partial functionality from the middleware. But with prone most of logic is encapsulated in a wrap-exception function so my question is what would be idiomatic way to solve this problem? Should I just try to port entire wrapper? I'm mostly puzzled by things like debug/_debug-data_ and why it's always empty for my errors.

Thanks!

**Comment by magnars** [comment]
I don't have any experience with alpeh, but yeah, seems like you would have to port the entire wrapper. My guess about `debug-data` is that you're not using the `(debug)` function in `prone.debug`. Do let me know how it goes!
