### ISSUE TITLE
error from prone.js

### ISSUE THREAD

**Issue by FongHou** [magnars/prone#40]
Hi,

Getting this error from prone javascript code.

`Uncaught Error: Could not find tag parser for :prone.prep in ("inst" "uuid" "queue" "js")`

It seems cljs.reader not able to read tagged value sent by prone server. How to resolve this?

Thanks!

**Comment by magnars** [comment]
I'll take a look. Thanks for the report!

**Comment by magnars** [comment]
Turns out that the new edn serializer uses the recent clojure shorthand for maps with namespaced keywords - but that the clojurescript parser in Prone doesn't understand it. Looks like it's time to update the cljs-version in Prone.

**Comment by magnars** [comment]
Turns out that the versions in Prone are really old. I'll have to fight the upgrades for a while. Downgrade to Clojure 1.8 to work around this problem for now.

**Comment by FongHou** [comment]
Thanks for looking into it. Yes, was using 1.9.0-alpha10. Downgrade to 1.8 did get rid of tagged edn literal for prone/prep. However, got another error for linked/map which comes from a composure-api dependency that uses custom tag reader 

https://github.com/frankiesardo/linked/blob/master/src/data_readers.clj

Does this mean prone need all custom tag parsers on both client/server? This seems limiting its usage. Could this problem be solved by using transit instead of edn?

**Comment by magnars** [comment]
The data sent from the server has be parseable by the frontend, indeed. Maybe transit solves that? Worth a shot, I'd say. PR welcome.

**Comment by theronic** [comment]
Unable to use Prone with Clojure 1.9, because I need spec for data validation.
I hope this can be addressed soon, because I really miss Prone :)

**Comment by magnars** [comment]
I'll give this a shot now. Thanks for reminding me, @theronic.

**Comment by magnars** [comment]
@theronic @FongHou Could you please try `[prone "1.1.5-SNAPSHOT"]` and see if that solves your issues?

**Comment by magnars** [comment]
The `1.2.0` version of prone is built with the latest Clojure and ClojureScript versions, which should fix this issue. My testing seems to verify that. Please re-open if that is not the case for you.
