### ISSUE TITLE
prone 1.1.2's prone.js causes a SyntaxError

### ISSUE THREAD

**Issue by saeidscorp** [magnars/prone#43]
After upgrading to prone 1.1.2 this error occurs in `prone.js` line 22055:

> Uncaught SyntaxError: Invalid regular expression: /[A-Za-zÀ-ÖØ-öø-??-??-???-??-??-?]/: Range out of order in character class

prone 1.1.1 works fine but 1.1.2 fails on Firefox/Chrome/IE/...
Is it a problem with server response encoding maybe?

**Comment by magnars** [comment]
If you're still using Prone, could you see if this happens in `1.1.5-SNAPSHOT`? I have upgraded all dependencies. It was sorely needed.

**Comment by magnars** [comment]
I believe this is fixed in `1.2.0`, which explicitly sets char-set to utf-8. Please re-open if this is not the case.
