### ISSUE TITLE
Prone does not catch AssertionErrors

### ISSUE THREAD

**Issue by alephyud** [magnars/prone#44]
At the moment `prone` catches [only](https://github.com/magnars/prone/blob/master/src/prone/middleware.clj#L126) `java.lang.Exception`s - which does not include `AssertionError`s, among other error classes.

Is it intentional? Since `prone` is used in development, it would be good to be use it for debugging the code with assertions and pre- and post-conditions.

Would you consider making `prone`'s middleware catch all `Error`s (or even any `Throwable`)? Or, alternatively, is there any other way to have the debug output for assertion failures?

**Comment by magnars** [comment]
Good question. We don't want to catch OOM-errors and such. Maybe we could just add AssertionError to the list?

**Comment by alephyud** [comment]
Maybe - but what's wrong with OOM errors? If my program runs out of memory in development (which is most likely due to a bug in my code), I would like to know where exactly this happens.

Actually, in the list of [Error subclasses](https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html), I don't see any single error type I would not like to catch in development.

**Comment by magnars** [comment]
Prone would not be able to do its work to show the error if the JVM has no memory.

**Comment by alephyud** [comment]
Right. I didn't understood well enough how JVM works.

Then maybe just catching Exception and AssertionError would be a good idea?

**Comment by magnars** [comment]
Yes, that would make sense.

**Comment by alephyud** [comment]
Ok - submitted a [pull request](https://github.com/magnars/prone/pull/45).

**Comment by magnars** [comment]
Closed via #45
