### ISSUE TITLE
NodeJS

### ISSUE THREAD

**Issue by au-phiware** [magnars/prone#46]
Have you thought of porting prone to nodejs?

I would like to see this and I don't mind contributing. Do you have any pointers?

**Comment by magnars** [comment]
Something like this? https://www.npmjs.com/package/express-exceptions

**Comment by au-phiware** [comment]
I think prone has a lot more going for (filtered backtrace, debug, drill into data, etc.) And I'd be curious if source mapping works.

**Comment by magnars** [comment]
Are you considering this for running ClojureScript on NodeJS as a backend,
or for straight up JS?

**Comment by au-phiware** [comment]
Oh, sorry, yes, NodeJS.

**Comment by magnars** [comment]
That would be out of scope for this project, but you are certainly free to use this code as a start when porting to NodeJS. :) Best of luck!
