### ISSUE TITLE
Skip certain exception

### ISSUE THREAD

**Issue by rspacjer** [magnars/prone#47]
Hi,

I have a web app, in which I use [buddy-auth](https://github.com/funcool/buddy-auth) and prone (in dev mode).

I've implemented session authentication same as in this [example](https://github.com/funcool/buddy-auth/blob/master/examples/session/src/authexample/web.clj).

In this example if user is not authenticated then the exception is raised:
```
(defn home
  [request]
  (if-not (authenticated? request)
    (throw-unauthorized)
    (let [content (slurp (io/resource "index.html"))]
      (render content request))))
``` 
This exception should be handled then by the buddy code:
```
(def auth-backend
  (session-backend {:unauthorized-handler unauthorized-handler}))
```

but in the development mode this doesn't work, because **prone** is catching and handling this exception. Is there any way to pass it down, to the  unauthorized-handler?

Thanks in advance!

**Comment by magnars** [comment]
Sounds like the prone-middleware is too close to the app handler - maybe you can rearrange the middlewares so that buddy has a chance to catch it first?

**Comment by rspacjer** [comment]
Yes, this has solved a problem. Thanks for pointing me the solution and sorry for trouble.

Regards!
