### ISSUE TITLE
Missing content-type header (assets)

### ISSUE THREAD

**Issue by semaperepelitsa** [magnars/prone#54]
I understand that content-type header is technically not required, however it seems like a best practice to include it whenever possible. For example, Rails includes content-type when serving assets. Do you think it can be included here as well? The resources missing content-type are prone.js and prone.css.

```
HTTP/1.1 200 OK
Cache-Control: max-age=315360000
X-Runtime: 6.317E-6
Content-Length: 3402889
Server: http-kit
Date: Tue, 16 Jun 2020 17:27:21 GMT
```

The reason why I noticed this is that we have Clojure server sitting behind a reverse proxy, and when the proxy handles a response, it automatically sets missing content-type to default - text/plain. This makes browsers ignore assets, breaking the debug page.

**Comment by magnars** [comment]
Yes, this makes sense. I have always used the ring content-type middleware, but that shouldn't be required. I'll look into it.

**Comment by magnars** [comment]
Sorry about the delay. This issue was in email purgatory. Fixed with `2021-04-23`.
